### ISSUE TITLE
[Bug]: Portal 2 stutters massively every few seconds

### ISSUE THREAD

**Issue by unilock** [Kegworks-App/Kegworks#16]
### macOS Version

Sequoia (macOS 15)

### Apple Silicon or Intel

Apple Silicon

### Wrapper Version

Wineskin-3.0.8 (though the wrapper configuration reports itself as version 3.0.7?)

### Engine

WS12WineCX23.7.1

### Application/Game Name

Portal 2

### Render Used

Not sure - probably whichever is default (WineD3D?)

### Description of problem

While Portal 2 is running, every few seconds, it stutters massively - the game freezes and the audio loops over itself a few times before unfreezing.

### Steps to reproduce

1. Install Steam via Kegworks
2. Install Portal 2 via Steam
3. Start Portal 2
4. Try clicking around menus for a minute or two
5. The game stutters quite a bit

### Expected behavior

The game runs smoothly.

### LastRunWineLog

(Where do I find LastRunWine.log? The `/Contents/SharedSupport/Logs` folder is empty.)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Notes

- Deleting `/Contents/Frameworks/renderer/d3dmetal/2.0`, as discussed in #9, does not seem to help.
- Toggling "MoltenVK FastMath" in the Steam wrapper's configuration makes no difference.

**Comment by unilock** [comment]
> Try installing `d9vk` winetricks verb.

After installing `d9vk` via winetricks, the game is now much more broken than before. The screen remains entirely black - although, intermittently, parts of the background and the menu options will sometimes appear. Moving the mouse cursor over the menu options still makes sound and can still be clicked - unfortunately, this is how I know that the original stuttering issue is also still present...

The `LastRunWine.log` from a "Test Run": https://gist.github.com/unilock/b13ff4032a55c6dce1b93d101c56be43

Note that this is with the default wrapper settings (besides `d9vk` from winetricks) - "D3DMetal/GPTK" and "MoltenVK FastMath" are both disabled. However, the same (new) issues occur with those options enabled as well.

**Comment by KOT-OPET** [comment]
strange — I've got _the exact same game with the exact same engine_ and it works flawlessly. Ok, sometimes there _are_ momentary shutters when approaching portals, but I wouldn't call it significant by any means. I never used d9vk, so my wrapper use the default WineD3D, I guess.  

I have M3 mac with 16gb memory. I use 1440x900 resolution, all graphics settings are medium, and my mac is in low power mode, since I don't like it getting hot while I'm playing. 

Hope that helps.

**Comment by KOT-OPET** [comment]
Well, I have the overlay enabled, but it wouldn't hurt to disable it, yes.

I forgot to mention I selected "Windows 10" in wine config utility:
<img width="522" alt="Screenshot 2024-10-28 at 09 22 40" src="https://github.com/user-attachments/assets/d836a3cc-3124-43c8-b377-be62cb85f915">

The default setting was "Windows 7", and steam was barely usable, with constant crashing of steamwebhelper etc. Switching to 10 solved the problem. Maybe make it default, or at least make the selection available from the main settings window?

**Comment by unilock** [comment]
@Gcenx
> ...I seem to remember a note about the Steam overlay causing problems on some systems...

Disabling the Steam Overlay appears to have fixed things! I'll close this issue, but if it needs further investigation to come up with a proper fix, feel free to re-open it. For reference, I'm using a Apple MacBook Air M2, 8-core CPU / 8-core GPU, 13-inch.

@KOT-OPET
> The default setting was "Windows 7", and steam was barely usable, with constant crashing of steamwebhelper etc. Switching to 10 solved the problem. Maybe make it default, or at least make the selection available from the main settings window?

For what it's worth, the default setting was "Windows 10" for me.

**Comment by KOT-OPET** [comment]
>  the default setting was "Windows 10"

I might have messed with different wine-related pieces of software for too long. Maybe win 7 was the default setting in portingkit, not in Kegworks. The described case with steam definitely was real, but now I doubt if it was in Kegworks. Sorry :-)
