### ISSUE TITLE
Transferring Wrappers

### ISSUE THREAD

**Issue by NellowTCS** [Kegworks-App/Kegworks#32]
I have a quick question.
If I copy **only** the wrapper for an app to a different Mac will it work? If not what else do I need to move?

**Comment by NellowTCS** [comment]
Thanks!

**Comment by MichaelScherf** [comment]
I always copy wrappers from Mac mini to my MacBook Pro without any issues. Only the validation starts from scratch.

**Comment by NellowTCS** [comment]
Okay thanks y'all! I'm going to close the issue.
